# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Andrei Sas
subtitle: cinematographer
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
    cinematographer based in London
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

imdb: name/nm5499550/
instagram: andreisas_dop
vimeo: andreisas
linkedin: andrei-sas
twitter: andreisas_dop

# Collections
# Add .md files for each collection item in collection subfolders
collections_dir: videos
collections:
    narrative:
        output: true
        permalink: /narrative/:path/
    commercial:
        output: true
        permalink: /commercial/:path/
    music:
        output: true
        permalink: /music/:path/
    photography:
        output: true
        permalink: /photography/:path/

# Specify default template for collections
defaults:
  - scope:
      path: ""
      type: "music"
    values:
      layout: "video-item"
  - scope:
      path: ""
      type: "narrative"
    values:
      layout: "video-item"
  - scope:
      path: ""
      type: "commercial"
    values:
      layout: "video-item"
  - scope:
      path: ""
      type: "photography"
    values:
      layout: "photo-item"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"


# Build settings
theme: minima

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
